site_name: MkDocs Software Printer User Guide
site_url: https://spirit-riddle.github.io/mkdocs-software-printer/
base_url: /mkdocs-software-printer/
nav:
  - Home: ./user-guide/index.md
  - Introduction: ./user-guide/01_introduction.md
  - Features: ./user-guide/02_features.md
  - Installation: ./user-guide/03_installation.md
  - Configuration: ./user-guide/04_configuration.md
  - Usage: ./user-guide/05_usage.md
  - Workflow Overview: ./user-guide/06_workflow_overview.md
  - Advanced Features: ./user-guide/07_advanced_features.md
  - Troubleshooting: ./user-guide/08_troubleshooting.md
  - FAQ: ./user-guide/09_faq.md
  - Support and Contributions: ./user-guide/10_support_and_contributions.md
  - License: ./user-guide/11_license.md
  - System Documentation: /mkdocs-software-printer/system/index.html
theme:
  name: material
  custom_dir: docs/overrides

markdown_extensions:
  - admonition
  - toc:
      permalink: true      
  - codehilite:
      guess_lang: false
      linenums: true
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.superfences

extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/js/all.min.js
